import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlignLeft,
  AppWindow,
  Award,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  Box,
  Brackets,
  Calendar,
  CheckCircle2,
  CheckSquare,
  Circle,
  CircleChevronDown,
  ChevronsLeftRight,
  ChevronsRight,
  ChevronsUpDown,
  ClipboardList,
  Clock,
  Code2,
  Columns2,
  CreditCard,
  DollarSign,
  Frame,
  GalleryHorizontal,
  Gauge,
  Ghost,
  Hash,
  Heading1,
  History,
  Image,
  Inbox,
  Kanban,
  Laptop,
  LayoutGrid,
  LayoutList,
  LineChart,
  List,
  ListFilter,
  Loader,
  Loader2,
  Lock,
  LogIn,
  Mail,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessagesSquare,
  Minus,
  Monitor,
  MousePointerClick,
  Music2,
  Palette,
  PanelBottom,
  PanelBottomOpen,
  PanelLeft,
  PanelRight,
  PanelTop,
  PieChart,
  PlusSquare,
  RectangleHorizontal,
  Rows3,
  Search,
  Settings2,
  Smartphone,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareStack,
  Table2,
  Tag,
  Tags,
  TextCursorInput,
  ToggleLeft,
  Type,
  Upload,
  User,
  UserRound,
  Video,
  Wrench,
} from "lucide-react";
import type { SceneNodeType } from "./types";

const BY_KEY: Record<string, LucideIcon> = {
  FRAME: Frame,
  FRAME_IDE: Monitor,
  FRAME_DESKTOP: AppWindow,
  FRAME_APP: Smartphone,
  FRAME_WIDE: RectangleHorizontal,
  CONTAINER: Box,
  PANEL: PanelRight,
  GRID: LayoutGrid,
  FLEX_ROW: Rows3,
  FLEX_COL: Columns2,
  DIVIDER: Minus,
  SPACER: SquareStack,
  RECTANGLE: Square,
  TEXT: Type,
  HEADING: Heading1,
  PARAGRAPH: AlignLeft,
  BUTTON: MousePointerClick,
  BUTTON_SECONDARY: SquareStack,
  BUTTON_OUTLINE: Square,
  BUTTON_GHOST: Ghost,
  BUTTON_ICON: PlusSquare,
  IMAGE: Image,
  ICON: Sparkles,
  AVATAR: UserRound,
  INPUT: TextCursorInput,
  INPUT_PASSWORD: Lock,
  INPUT_EMAIL: Mail,
  INPUT_NUMBER: Hash,
  CHECKBOX: CheckSquare,
  RADIO: Circle,
  SWITCH: ToggleLeft,
  SELECT: ListFilter,
  DROPDOWN: CircleChevronDown,
  TEXTAREA: Brackets,
  LABEL: Tag,
  LIST: List,
  CARD: CreditCard,
  CODE_BLOCK: Code2,
  MARKDOWN: BookOpen,
  MODAL: Maximize2,
  DRAWER: PanelBottomOpen,
  TOAST: Bell,
  NAVBAR: Menu,
  SIDEBAR: PanelLeft,
  FOOTER: PanelBottom,
  TABS: LayoutList,
  ACCORDION: ChevronsUpDown,
  BREADCRUMBS: ChevronsRight,
  BADGE: Award,
  TAG: Tags,
  TOOLTIP: MessageCircle,
  PROGRESS: Loader,
  SLIDER: SlidersHorizontal,
  SPINNER: Loader2,
  SKELETON: Minus,
  ALERT: AlertCircle,
  NOTIFICATION: BellRing,
  TABLE: Table2,
  PAGINATION: ChevronsLeftRight,
  SEARCH_BAR: Search,
  VIDEO_PLAYER: Video,
  AUDIO_PLAYER: Music2,
  CAROUSEL: GalleryHorizontal,
  CHART_BAR: BarChart3,
  CHART_LINE: LineChart,
  CHART_PIE: PieChart,
  DATE_PICKER: Calendar,
  TIME_PICKER: Clock,
  COLOR_PICKER: Palette,
  FILE_UPLOADER: Upload,
  HERO_SECTION: Sparkles,
  PRICING_CARD: DollarSign,
  CTA_SECTION: Megaphone,
  FORM: ClipboardList,
  LOGIN_FORM: LogIn,
  SETTINGS_PANEL: Settings2,
  STATS_WIDGET: Activity,
  GAUGE: Gauge,
  MAP_PLACEHOLDER: MapPin,
  TIMELINE: History,
  KANBAN_COLUMN: Kanban,
  CHAT_BUBBLE: MessageCircle,
  COMMENT_THREAD: MessagesSquare,
  USER_PROFILE: User,
  EMPTY_STATE: Inbox,
  ERROR_STATE: AlertOctagon,
  SUCCESS_STATE: CheckCircle2,
  TOPBAR_WIN: AppWindow,
  TOPBAR_MAC: Laptop,
  TOPBAR_CUSTOM: Wrench,
};

const BY_TYPE: Partial<Record<SceneNodeType, LucideIcon>> = {
  FRAME: Frame,
  TEXT: Type,
  BUTTON: MousePointerClick,
  INPUT: TextCursorInput,
  IMAGE: Image,
  ICON: Sparkles,
  CONTAINER: Box,
  PANEL: PanelRight,
  LIST: List,
  CHECKBOX: CheckSquare,
  SELECT: ListFilter,
  DIVIDER: Minus,
  SPACER: SquareStack,
  RECTANGLE: Square,
  TOPBAR: PanelTop,
  COMPONENT: Box,
};

export function getComponentPresetIcon(presetKey: string, nodeType: SceneNodeType): LucideIcon {
  return BY_KEY[presetKey] ?? BY_TYPE[nodeType] ?? Box;
}
